version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      backend:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USER_NAME}/ui:logging
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - frontend
  post:
    image: ${USER_NAME}/post:logging
    networks:
      backend:
        aliases:
          - post
      frontend:
        aliases:
          - post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:logging
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      backend:
        aliases:
          - comment
      frontend:
        aliases:
          - comment

  prometheus:
    image: ${USER_NAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - backend
      - frontend

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - frontend
      - backend

  mongodb-exporter:
    image: bitnami/mongodb-exporter:0.30.0
    ports:
      - '9216:9216'
    command: # Передаем доп параметры в командной строке
      - '--mongodb.uri=mongodb://post_db:27017'
    networks:
      - frontend
      - backend

volumes:
  post_db:
  prometheus_data:

networks:
  frontend:
  backend:
