version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - ${POST_DB_NETWORK}
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - ${UI_NETWORK}
  post:
    build: ./post-py
    image: ${USERNAME}/post:${POST_TAG}
    networks:
      - backend
      - frontend
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - backend
      - frontend

volumes:
  post_db:

networks:
  frontend:
  backend:
