---
# tasks file for roles/docker_install
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ required_packages }}"

- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_repo_key }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install docker and its dependecies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    force: true
  loop: "{{ docker_packages }}"

- name: Ensure user added to the docker group.
  user:
    name: "{{ docker_user }}"
    groups: "{{ docker_group }}"
    append: true
